version: "3"
services:
  weeve-email:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: weeve-email
      MODULE_TYPE: EGRESS
      EGRESS_URL: https://hookb.in/OekpN3YnVKTqOdYYxb22
      INPUT_LABEL: "temperature"
      SENDER_EMAIL_ID: "mithila.ghuge@weeve.network"
      RECIPENT_EMAIL_ID: 
      EMAIL_SUBJECT: "Test Module"
      EMAIL_BODY: "Data point {{label}} reached the value of {{value}} {{unit}} at {{time}}!"
      ATTACHMENT_FILE_PATH: "/app/image/src/app/module/client_secret.json"
      SENDER_PASS: "Alwaysmine@0512"
    ports:
      - 5000:80
