version: "3"
services:
  weeve-email:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: weeve-email
      MODULE_TYPE: EGRESS
      EGRESS_URL: https://hookb.in/OekpN3YnVKTqOdYYxb22
      INPUT_LABEL: "temperature"
      RECIPENT_EMAIL_ID: "mithila.ghuge@weeve.network"
      AUTH_TOKEN: {"installed":{"client_id":"977032374127-3k9h2bctin0adrqi1iq0cep614ttjlkk.apps.googleusercontent.com","project_id":"emailmoduleweeve","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost"]}}
      EMAIL_SUBJECT : "Test Module"
      EMAIL_BODY : "Data point {{label}} reached the value of {{value}} {{unit}} at {{time}}!"
      ATTACHMENT_FILE_PATH : "/Users/mithila/Documents/raspberry.png"
    ports:
      - 5000:80
